# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "backendFinal", "BugFixesDoneTesting", "backendTesting" ]
  pull_request:
    branches: [ "backendFinal", "BugFixesDoneTesting", "backendTesting"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

  strategy:
    matrix:
      node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3 
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run lint
