name: backend test

on:
  push:
    branches: [ "backendFinal", "BugFixesDoneTesting", "backendTesting" ]
  pull_request:
    branches: [ "backendFinal", "BugFixesDoneTesting", "backendTesting"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
      - name: execute py script # run file
        run: |
          python "backend\test.py"